version: 0.0
os: linux

files:
  - source: files/index.html
    destination: /var/www/html
  
permissions:
  - object: /var/www/html
    pattern: index.html
    owner: apache
    group: apache
    mode: 644
    type:
      - file
    
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
<<<<<<< HEAD
      runas: root
=======
>>>>>>> 037285c9b83fe02d292084c4e5dfbc72baef8110
    #- location: scripts/deregister_from_elb.sh
    - location: scripts/webserver-stop.sh
    - location: scripts/delete-old-index.sh
  AfterInstall:
    - location: scripts/sleep.sh
    - location: scripts/webserver-start.sh
    #- location: scripts/register_with_elb.sh
  
